### ISSUE TITLE
Invalid string for LTSpice call from eec.runSpiceNetlist method

### ISSUE THREAD

**Issue by Masltov** [mhorsche/matlab-eec#2]
Execution of line 905 of eec Class throws Exception.
_sprintf("%s -b %s",eecmodel.SpicePath,netlistName)_ results in _"C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe -b eec.cir"_ 
or execution string _C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe -b eec.cir_ in Windows cmd. 
Whitespace within _C:\**Program Files**\LTC\LTspiceXVII\XVIIx64.exe_ cannot be handled

Solution: String of eecmodel.SpicePath must be quoted so that execution string is _"C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe" -b eec.cir_
Proposal: Change line 905 of eec class to _res = system(sprintf(['"', '%s', '"', ' -b %s'],eecmodel.SpicePath,netlistName));_

System information:
- Win 10 x64
- MATLAB 2020b
- LTSpice XVII x64

**Comment by mhorsche** [comment]
Thanks for your comment, I changed line 905 to:

`res = system(sprintf('"%s" -b %s',eecmodel.SpicePath,netlistName));`

which should have the same effect and is more readable. Maybe you can confirm it's working correctly, since I'm using OS X.

**Comment by Masltov** [comment]
Proposed solution verified.

Issue will be closed, sorry for the delay ;)
Thanx
